workspace:
  base: /drone
  path: src/nexus-stats

pipeline:
  build:
    image: 127.0.0.1:5000/nexus-stats-dev
    commands:
      - npm install
      - npm run build
  stage:
    image: 127.0.0.1:5000/drone-staging
    commands:
      - /bin/sh /stage.sh /drone/src/nexus-stats development staging
    secrets:
      - nexus-ci-user
      - nexus-ci-pass
  test:
    image: 127.0.0.1:5000/drone-staging
    commands:
      - /bin/sh /deploy.sh
      - npm run test
      - /bin/sh /undeploy.sh
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock