pipeline:

  # All
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint

  # Development
  test - development:
    image: node
    commands:
      - npm test
    when:
      branch: development
  stage:
    image: node
    commands:
      - git fetch --all
      - git checkout staging
      - git merge -s recursive -X theirs origin/development
      - git push 'https://nexus-ci:'$NEXUS_CI_TOKEN'@github.com/nexus-devs/nexus-stats' staging 2>/dev/null
    secrets: [ nexus_ci_token ]
    when:
      branch: development

  # Staging
  test - production:
    image: node
    commands:
      - npm run build
      - npm test --production
    when:
      branch: staging
  deploy:
    image: node
    commands:
      - echo "We're not quite there yet 😉"
    when:
      branch: staging

  # Final release to production
  release:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npm run release
    secrets: [ gh_token ]
    when:
      branch: master

services:
  mongodb:
    image: mongo
  redis:
    image: redis