pipeline:
  build:
    image: node
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test - development:
    image: node
    commands:
      - npm test
  test - production:
    image: node
    commands:
      - npm run build
      - npm test --production
  stage:
    image: node
    commands:
      - git merge -s recursive -X theirs staging
    when:
      branch: development
  deploy:
    image: node
    commands:
      - echo "We're not quite there yet 😉"
    when:
      branch: staging
  release:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npm run publish
    secrets: [ gh_token ]
    when:
      branch: master

services:
  mongodb:
    image: mongo
  redis:
    image: redis